services:
  mysql:
    image: mysql:8.0
    container_name: pokeapi-sqlserver
    environment:
      MYSQL_ROOT_PASSWORD: Root@1234
      MYSQL_DATABASE: pokeapi_database
      MYSQL_USER: user
      MYSQL_PASSWORD: Password@1234
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local
