services:
  mysql:
    image: mysql:8.0
    container_name: pokeapi-sqlserver
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - '3306:${DB_PORT}'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local
